from attribute_utils.attributes_action import get_attribute_action
from attribute_utils.attributes_answer_type import get_answer_type
from attribute_utils.attributes_default_utils import get_attribute_product, get_attribute_named_entity
from attribute_utils.attributes_location import get_attribute_location_spacy
from attribute_utils.attributes_question_type import get_question_type
from attribute_utils.attributes_time import get_attribute_time_spacy
