from attributes_action import get_attribute_action
from attributes_answer_type import get_answer_type
from attributes_default_utils import get_attribute_product, get_attribute_named_entity
from attributes_location import get_attribute_location_spacy
from attributes_question_type import get_question_type
from attributes_time import get_attribute_time_spacy
